[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = "warn"
nursery = "warn"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
thiserror = "2.0.5"
